<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('countries')->insert([
            [
                'name' => 'Afghanistan',
                'code' => 93,
                'fax_price' => 1,
                'iso_code' => 'AF',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Albania',
                'code' => 355,
                'fax_price' => 1,
                'iso_code' => 'AL',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Algeria',
                'code' => 213,
                'fax_price' => 1,
                'iso_code' => 'DZ',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Andorra',
                'code' => 376,
                'fax_price' => 1,
                'iso_code' => 'AD',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Angola',
                'code' => 244,
                'fax_price' => 1,
                'iso_code' => 'AO',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Anguilla',
                'code' => 264,
                'fax_price' => 1,
                'iso_code' => 'AI',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Antigua and Barbuda',
                'code' => 268,
                'fax_price' => 1,
                'iso_code' => 'AG',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Argentina',
                'code' => 54,
                'fax_price' => 1,
                'iso_code' => 'AR',
                'continent' => 'South America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Armenia',
                'code' => 374,
                'fax_price' => 1,
                'iso_code' => 'AM',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Austria',
                'code' => 43,
                'fax_price' => 1,
                'iso_code' => 'AT',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Azerbaijan',
                'code' => 994,
                'fax_price' => 1,
                'iso_code' => 'AZ',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bahamas',
                'code' => 242,
                'fax_price' => 1,
                'iso_code' => 'BS',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bahrain',
                'code' => 973,
                'fax_price' => 1,
                'iso_code' => 'BH',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bangladesh',
                'code' => 880,
                'fax_price' => 2,
                'iso_code' => 'BD',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Barbados',
                'code' => 246,
                'fax_price' => 2,
                'iso_code' => 'BB',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Belarus',
                'code' => 375,
                'fax_price' => 2,
                'iso_code' => 'BY',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Belgium',
                'code' => 32,
                'fax_price' => 2,
                'iso_code' => 'BE',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Belize',
                'code' => 501,
                'fax_price' => 2,
                'iso_code' => 'BZ',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Benin',
                'code' => 229,
                'fax_price' => 6,
                'iso_code' => 'BJ',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bermuda',
                'code' => 440,
                'fax_price' => 2,
                'iso_code' => 'BM',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bhutan',
                'code' => 975,
                'fax_price' => 2,
                'iso_code' => 'BT',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bolivia',
                'code' => 591,
                'fax_price' => 2,
                'iso_code' => 'BO',
                'continent' => 'South America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bosnia Herzegovina',
                'code' => 387,
                'fax_price' => 2,
                'iso_code' => 'BA',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Botswana',
                'code' => 267,
                'fax_price' => 2,
                'iso_code' => 'BW',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Brazil',
                'code' => 55,
                'fax_price' => 2,
                'iso_code' => 'BR',
                'continent' => 'South America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Brunei',
                'code' => 673,
                'fax_price' => 2,
                'iso_code' => 'BN',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bulgaria',
                'code' => 359,
                'fax_price' => 2,
                'iso_code' => 'BG',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Burkina Faso',
                'code' => 226,
                'fax_price' => 2,
                'iso_code' => 'BF',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Burundi',
                'code' => 257,
                'fax_price' => 2,
                'iso_code' => 'BI',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cambodia',
                'code' => 855,
                'fax_price' => 2,
                'iso_code' => 'KH',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cameroon',
                'code' => 237,
                'fax_price' => 2,
                'iso_code' => 'CM',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Canada',
                'code' => 1,
                'fax_price' => 2,
                'iso_code' => 'CA',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cape Verde',
                'code' => 238,
                'fax_price' => 2,
                'iso_code' => 'CV',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cayman Islands',
                'code' => 344,
                'fax_price' => 2,
                'iso_code' => 'KY',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Central African Republic',
                'code' => 236,
                'fax_price' => 2,
                'iso_code' => 'CF',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chad',
                'code' => 235,
                'fax_price' => 2,
                'iso_code' => 'TD',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chile',
                'code' => 56,
                'fax_price' => 2,
                'iso_code' => 'CL',
                'continent' => 'South America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'China',
                'code' => 86,
                'fax_price' => 2,
                'iso_code' => 'CN',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Colombia',
                'code' => 57,
                'fax_price' => 2,
                'iso_code' => 'CO',
                'continent' => 'South America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Comoros',
                'code' => 269,
                'fax_price' => 2,
                'iso_code' => 'KM',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Congo',
                'code' => 242,
                'fax_price' => 2,
                'iso_code' => 'CG',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Congo (DRC)',
                'code' => 243,
                'fax_price' => 2,
                'iso_code' => 'CD',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cook Islands',
                'code' => 682,
                'fax_price' => 2,
                'iso_code' => 'CK',
                'continent' => 'Australia and Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Costa Rica',
                'code' => 506,
                'fax_price' => 2,
                'iso_code' => 'CR',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cote d\'Ivoire',
                'code' => 225,
                'fax_price' => 2,
                'iso_code' => 'CI',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Croatia',
                'code' => 385,
                'fax_price' => 2,
                'iso_code' => 'HR',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cuba',
                'code' => 53,
                'fax_price' => 2,
                'iso_code' => 'CU',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cyprus',
                'code' => 357,
                'fax_price' => 2,
                'iso_code' => 'CY',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Czech Republic',
                'code' => 420,
                'fax_price' => 2,
                'iso_code' => 'CZ',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Denmark',
                'code' => 45,
                'fax_price' => 2,
                'iso_code' => 'DK',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Djibouti',
                'code' => 253,
                'fax_price' => 2,
                'iso_code' => 'DJ',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dominica',
                'code' => 766,
                'fax_price' => 2,
                'iso_code' => 'DM',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dominican Republic',
                'code' => 809,
                'fax_price' => 2,
                'iso_code' => 'DO',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'East Timor',
                'code' => 670,
                'fax_price' => 2,
                'iso_code' => 'TL',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ecuador',
                'code' => 593,
                'fax_price' => 2,
                'iso_code' => 'EC',
                'continent' => 'South America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Egypt',
                'code' => 20,
                'fax_price' => 2,
                'iso_code' => 'EG',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'El Salvador',
                'code' => 503,
                'fax_price' => 2,
                'iso_code' => 'SV',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Equatorial Guinea',
                'code' => 240,
                'fax_price' => 2,
                'iso_code' => 'GQ',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Eritrea',
                'code' => 291,
                'fax_price' => 2,
                'iso_code' => 'ER',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Estonia',
                'code' => 372,
                'fax_price' => 2,
                'iso_code' => 'EE',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ethiopia',
                'code' => 251,
                'fax_price' => 2,
                'iso_code' => 'ET',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Falkland Islands',
                'code' => 500,
                'fax_price' => 2,
                'iso_code' => 'FK',
                'continent' => 'South America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Faroe Islands',
                'code' => 298,
                'fax_price' => 3,
                'iso_code' => 'FO',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fiji',
                'code' => 679,
                'fax_price' => 3,
                'iso_code' => 'FJ',
                'continent' => 'Australia and Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Finland',
                'code' => 358,
                'fax_price' => 3,
                'iso_code' => 'FI',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'France',
                'code' => 33,
                'fax_price' => 3,
                'iso_code' => 'FR',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'French Guiana',
                'code' => 594,
                'fax_price' => 3,
                'iso_code' => 'GF',
                'continent' => 'South America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'French Polynesia',
                'code' => 689,
                'fax_price' => 3,
                'iso_code' => 'PF',
                'continent' => 'Australia and Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gabon',
                'code' => 241,
                'fax_price' => 3,
                'iso_code' => 'GA',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gambia',
                'code' => 220,
                'fax_price' => 3,
                'iso_code' => 'GM',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Georgia',
                'code' => 995,
                'fax_price' => 3,
                'iso_code' => 'GE',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Germany',
                'code' => 49,
                'fax_price' => 3,
                'iso_code' => 'DE',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ghana',
                'code' => 233,
                'fax_price' => 3,
                'iso_code' => 'GH',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gibraltar',
                'code' => 350,
                'fax_price' => 3,
                'iso_code' => 'GI',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Greece',
                'code' => 30,
                'fax_price' => 3,
                'iso_code' => 'GR',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Greenland',
                'code' => 299,
                'fax_price' => 3,
                'iso_code' => 'GL',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Grenada',
                'code' => 472,
                'fax_price' => 3,
                'iso_code' => 'GD',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Guadeloupe',
                'code' => 590,
                'fax_price' => 3,
                'iso_code' => 'GP',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Guam',
                'code' => 671,
                'fax_price' => 3,
                'iso_code' => 'GU',
                'continent' => 'Australia and Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Guatemala',
                'code' => 502,
                'fax_price' => 3,
                'iso_code' => 'GT',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Guinea',
                'code' => 224,
                'fax_price' => 3,
                'iso_code' => 'GN',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Guinea-Bissau',
                'code' => 245,
                'fax_price' => 3,
                'iso_code' => 'GW',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Guyana',
                'code' => 592,
                'fax_price' => 3,
                'iso_code' => 'GY',
                'continent' => 'South America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Haiti',
                'code' => 509,
                'fax_price' => 3,
                'iso_code' => 'HT',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Honduras',
                'code' => 504,
                'fax_price' => 3,
                'iso_code' => 'HN',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hong Kong',
                'code' => 852,
                'fax_price' => 3,
                'iso_code' => 'HK',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hungary',
                'code' => 36,
                'fax_price' => 3,
                'iso_code' => 'HU',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Iceland',
                'code' => 354,
                'fax_price' => 3,
                'iso_code' => 'IS',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'India',
                'code' => 91,
                'fax_price' => 3,
                'iso_code' => 'IN',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Indonesia',
                'code' => 62,
                'fax_price' => 3,
                'iso_code' => 'ID',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Iran',
                'code' => 98,
                'fax_price' => 3,
                'iso_code' => 'IR',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Iraq',
                'code' => 964,
                'fax_price' => 3,
                'iso_code' => 'IQ',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ireland',
                'code' => 353,
                'fax_price' => 3,
                'iso_code' => 'IE',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Israel',
                'code' => 972,
                'fax_price' => 3,
                'iso_code' => 'IL',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Italy',
                'code' => 39,
                'fax_price' => 3,
                'iso_code' => 'IT',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jamaica',
                'code' => 875,
                'fax_price' => 3,
                'iso_code' => 'JM',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Japan',
                'code' => 81,
                'fax_price' => 3,
                'iso_code' => 'JP',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jordan',
                'code' => 962,
                'fax_price' => 3,
                'iso_code' => 'JO',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kazakhstan',
                'code' => 7,
                'fax_price' => 3,
                'iso_code' => 'KZ',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kenya',
                'code' => 254,
                'fax_price' => 3,
                'iso_code' => 'KE',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kiribati',
                'code' => 686,
                'fax_price' => 3,
                'iso_code' => 'KI',
                'continent' => 'Australia and Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'South Korea',
                'code' => 82,
                'fax_price' => 3,
                'iso_code' => 'KR',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kuwait',
                'code' => 965,
                'fax_price' => 3,
                'iso_code' => 'KW',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kyrgyzstan',
                'code' => 996,
                'fax_price' => 3,
                'iso_code' => 'KG',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laos',
                'code' => 856,
                'fax_price' => 3,
                'iso_code' => 'LA',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Latvia',
                'code' => 371,
                'fax_price' => 3,
                'iso_code' => 'LV',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lebanon',
                'code' => 961,
                'fax_price' => 3,
                'iso_code' => 'LB',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lesotho',
                'code' => 266,
                'fax_price' => 3,
                'iso_code' => 'LS',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Liberia',
                'code' => 231,
                'fax_price' => 3,
                'iso_code' => 'LR',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Libya',
                'code' => 218,
                'fax_price' => 3,
                'iso_code' => 'LY',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Liechtenstein',
                'code' => 423,
                'fax_price' => 3,
                'iso_code' => 'LI',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lithuania',
                'code' => 370,
                'fax_price' => 3,
                'iso_code' => 'LT',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Luxembourg',
                'code' => 352,
                'fax_price' => 4,
                'iso_code' => 'LU',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Macao SAR',
                'code' => 853,
                'fax_price' => 4,
                'iso_code' => 'MO',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Macedonia',
                'code' => 389,
                'fax_price' => 4,
                'iso_code' => 'MK',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Madagascar',
                'code' => 261,
                'fax_price' => 4,
                'iso_code' => 'MG',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Malawi',
                'code' => 265,
                'fax_price' => 4,
                'iso_code' => 'MW',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Malaysia',
                'code' => 60,
                'fax_price' => 4,
                'iso_code' => 'MY',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maldives',
                'code' => 960,
                'fax_price' => 4,
                'iso_code' => 'MV',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mali',
                'code' => 223,
                'fax_price' => 4,
                'iso_code' => 'ML',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Malta',
                'code' => 356,
                'fax_price' => 4,
                'iso_code' => 'MT',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Marshall Islands',
                'code' => 692,
                'fax_price' => 6,
                'iso_code' => 'MH',
                'continent' => 'Australia and Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Martinique',
                'code' => 596,
                'fax_price' => 4,
                'iso_code' => 'MQ',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mauritania',
                'code' => 222,
                'fax_price' => 4,
                'iso_code' => 'MR',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mauritius',
                'code' => 230,
                'fax_price' => 4,
                'iso_code' => 'MU',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mayotte',
                'code' => 262,
                'fax_price' => 4,
                'iso_code' => 'YT',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mexico',
                'code' => 52,
                'fax_price' => 4,
                'iso_code' => 'MX',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Micronesia',
                'code' => 691,
                'fax_price' => 4,
                'iso_code' => 'FM',
                'continent' => 'Australia and Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Moldova',
                'code' => 373,
                'fax_price' => 4,
                'iso_code' => 'MD',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Monaco',
                'code' => 377,
                'fax_price' => 4,
                'iso_code' => 'MC',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mongolia',
                'code' => 976,
                'fax_price' => 4,
                'iso_code' => 'MN',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Montenegro',
                'code' => 382,
                'fax_price' => 6,
                'iso_code' => 'ME',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Montserrat',
                'code' => 663,
                'fax_price' => 4,
                'iso_code' => 'MS',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Morocco',
                'code' => 212,
                'fax_price' => 4,
                'iso_code' => 'MA',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mozambique',
                'code' => 258,
                'fax_price' => 4,
                'iso_code' => 'MZ',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Myanmar',
                'code' => 95,
                'fax_price' => 4,
                'iso_code' => 'MM',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Namibia',
                'code' => 264,
                'fax_price' => 4,
                'iso_code' => 'NA',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nauru',
                'code' => 674,
                'fax_price' => 4,
                'iso_code' => 'NR',
                'continent' => 'Australia and Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nepal',
                'code' => 977,
                'fax_price' => 4,
                'iso_code' => 'NP',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Netherlands',
                'code' => 31,
                'fax_price' => 4,
                'iso_code' => 'NL',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Netherlands Antilles',
                'code' => 599,
                'fax_price' => 4,
                'iso_code' => 'AN',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'New Caledonia',
                'code' => 687,
                'fax_price' => 4,
                'iso_code' => 'NC',
                'continent' => 'Australia and Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'New Zealand',
                'code' => 64,
                'fax_price' => 4,
                'iso_code' => 'NZ',
                'continent' => 'Australia and Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nicaragua',
                'code' => 505,
                'fax_price' => 4,
                'iso_code' => 'NI',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Niger',
                'code' => 227,
                'fax_price' => 4,
                'iso_code' => 'NE',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nigeria',
                'code' => 234,
                'fax_price' => 4,
                'iso_code' => 'NG',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Niue',
                'code' => 683,
                'fax_price' => 4,
                'iso_code' => 'NU',
                'continent' => 'Australia and Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Norfolk Island',
                'code' => 672,
                'fax_price' => 4,
                'iso_code' => 'NF',
                'continent' => 'Australia and Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'North Korea',
                'code' => 850,
                'fax_price' => 4,
                'iso_code' => 'KP',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Norway',
                'code' => 47,
                'fax_price' => 4,
                'iso_code' => 'NO',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Oman',
                'code' => 968,
                'fax_price' => 4,
                'iso_code' => 'OM',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pakistan',
                'code' => 92,
                'fax_price' => 4,
                'iso_code' => 'PK',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Palau',
                'code' => 680,
                'fax_price' => 6,
                'iso_code' => 'PW',
                'continent' => 'Australia and Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Palestine',
                'code' => 970,
                'fax_price' => 6,
                'iso_code' => 'PS',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Panama',
                'code' => 507,
                'fax_price' => 4,
                'iso_code' => 'PA',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Papua New Guinea',
                'code' => 675,
                'fax_price' => 4,
                'iso_code' => 'PG',
                'continent' => 'Australia and Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paraguay',
                'code' => 595,
                'fax_price' => 4,
                'iso_code' => 'PY',
                'continent' => 'South America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Peru',
                'code' => 51,
                'fax_price' => 4,
                'iso_code' => 'PE',
                'continent' => 'South America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Philippines',
                'code' => 63,
                'fax_price' => 4,
                'iso_code' => 'PH',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pitcairn Islands',
                'code' => 872,
                'fax_price' => 4,
                'iso_code' => 'PN',
                'continent' => 'Australia and Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Poland',
                'code' => 48,
                'fax_price' => 4,
                'iso_code' => 'PL',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Portugal',
                'code' => 351,
                'fax_price' => 4,
                'iso_code' => 'PT',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Puerto Rico',
                'code' => 787,
                'fax_price' => 4,
                'iso_code' => 'PR',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Qatar',
                'code' => 974,
                'fax_price' => 4,
                'iso_code' => 'QA',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Reunion',
                'code' => 262,
                'fax_price' => 4,
                'iso_code' => 'RE',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Romania',
                'code' => 40,
                'fax_price' => 4,
                'iso_code' => 'RO',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Russia',
                'code' => 7,
                'fax_price' => 5,
                'iso_code' => 'RU',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rwanda',
                'code' => 250,
                'fax_price' => 5,
                'iso_code' => 'RW',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Samoa',
                'code' => 685,
                'fax_price' => 5,
                'iso_code' => 'WS',
                'continent' => 'Australia and Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'San Marino',
                'code' => 378,
                'fax_price' => 5,
                'iso_code' => 'SM',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sao Tome and Principe',
                'code' => 239,
                'fax_price' => 5,
                'iso_code' => 'ST',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Saudi Arabia',
                'code' => 966,
                'fax_price' => 5,
                'iso_code' => 'SA',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Senegal',
                'code' => 221,
                'fax_price' => 5,
                'iso_code' => 'SN',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Serbia',
                'code' => 381,
                'fax_price' => 5,
                'iso_code' => 'RS',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Seychelles',
                'code' => 248,
                'fax_price' => 5,
                'iso_code' => 'SC',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sierra Leone',
                'code' => 232,
                'fax_price' => 5,
                'iso_code' => 'SL',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Singapore',
                'code' => 65,
                'fax_price' => 5,
                'iso_code' => 'SG',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Slovakia',
                'code' => 421,
                'fax_price' => 5,
                'iso_code' => 'SK',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Slovenia',
                'code' => 386,
                'fax_price' => 5,
                'iso_code' => 'SI',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Solomon Islands',
                'code' => 677,
                'fax_price' => 5,
                'iso_code' => 'SB',
                'continent' => 'Australia and Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Somalia',
                'code' => 252,
                'fax_price' => 5,
                'iso_code' => 'SO',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'South Africa',
                'code' => 27,
                'fax_price' => 6,
                'iso_code' => 'ZA',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Spain',
                'code' => 34,
                'fax_price' => 6,
                'iso_code' => 'ES',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sri Lanka',
                'code' => 94,
                'fax_price' => 6,
                'iso_code' => 'LK',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'St. Helena',
                'code' => 290,
                'fax_price' => 6,
                'iso_code' => 'SH',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'St. Kitts and Nevis',
                'code' => 868,
                'fax_price' => 6,
                'iso_code' => 'KN',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'St. Lucia',
                'code' => 757,
                'fax_price' => 6,
                'iso_code' => 'LC',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'St. Pierre and Miquelon',
                'code' => 508,
                'fax_price' => 6,
                'iso_code' => 'PM',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'St. Vincent',
                'code' => 783,
                'fax_price' => 6,
                'iso_code' => 'VC',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sudan',
                'code' => 249,
                'fax_price' => 6,
                'iso_code' => 'SD',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Suriname',
                'code' => 597,
                'fax_price' => 6,
                'iso_code' => 'SR',
                'continent' => 'South America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Swaziland',
                'code' => 268,
                'fax_price' => 6,
                'iso_code' => 'SZ',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sweden',
                'code' => 46,
                'fax_price' => 6,
                'iso_code' => 'SE',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Switzerland',
                'code' => 41,
                'fax_price' => 6,
                'iso_code' => 'CH',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Syria',
                'code' => 963,
                'fax_price' => 6,
                'iso_code' => 'SY',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Taiwan',
                'code' => 886,
                'fax_price' => 6,
                'iso_code' => 'TW',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tajikistan',
                'code' => 992,
                'fax_price' => 6,
                'iso_code' => 'TJ',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tanzania',
                'code' => 255,
                'fax_price' => 6,
                'iso_code' => 'TZ',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thailand',
                'code' => 66,
                'fax_price' => 6,
                'iso_code' => 'TH',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Togo',
                'code' => 228,
                'fax_price' => 6,
                'iso_code' => 'TG',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tokelau',
                'code' => 690,
                'fax_price' => 6,
                'iso_code' => 'TK',
                'continent' => 'Australia and Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tonga',
                'code' => 676,
                'fax_price' => 6,
                'iso_code' => 'TO',
                'continent' => 'Australia and Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Trinidad and Tobago',
                'code' => 867,
                'fax_price' => 6,
                'iso_code' => 'TT',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tunisia',
                'code' => 216,
                'fax_price' => 6,
                'iso_code' => 'TN',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Turkey',
                'code' => 90,
                'fax_price' => 6,
                'iso_code' => 'TR',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Turkmenistan',
                'code' => 993,
                'fax_price' => 6,
                'iso_code' => 'TM',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Turks and Caicos Islands',
                'code' => 648,
                'fax_price' => 6,
                'iso_code' => 'TC',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tuvalu',
                'code' => 688,
                'fax_price' => 6,
                'iso_code' => 'TV',
                'continent' => 'Australia and Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Uganda',
                'code' => 256,
                'fax_price' => 6,
                'iso_code' => 'UG',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ukraine',
                'code' => 380,
                'fax_price' => 6,
                'iso_code' => 'UA',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'United Arab Emirates',
                'code' => 971,
                'fax_price' => 6,
                'iso_code' => 'AE',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'United Kingdom',
                'code' => 44,
                'fax_price' => 6,
                'iso_code' => 'GB',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'United States',
                'code' => 1,
                'fax_price' => 6,
                'iso_code' => 'US',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Uruguay',
                'code' => 598,
                'fax_price' => 6,
                'iso_code' => 'UY',
                'continent' => 'South America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Uzbekistan',
                'code' => 998,
                'fax_price' => 6,
                'iso_code' => 'UZ',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vanuatu',
                'code' => 678,
                'fax_price' => 6,
                'iso_code' => 'VU',
                'continent' => 'Australia and Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Venezuela',
                'code' => 58,
                'fax_price' => 6,
                'iso_code' => 'VE',
                'continent' => 'South America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vietnam',
                'code' => 84,
                'fax_price' => 6,
                'iso_code' => 'VN',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'US Virgin Islands',
                'code' => 339,
                'fax_price' => 6,
                'iso_code' => 'VI',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'British Virgin Islands',
                'code' => 283,
                'fax_price' => 6,
                'iso_code' => 'VG',
                'continent' => 'North America',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wallis and Futuna',
                'code' => 681,
                'fax_price' => 6,
                'iso_code' => 'WF',
                'continent' => 'Australia and Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Western Sahara',
                'code' => 212,
                'fax_price' => 6,
                'iso_code' => 'EH',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yemen',
                'code' => 967,
                'fax_price' => 6,
                'iso_code' => 'YE',
                'continent' => 'Asia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yugoslavia',
                'code' => 381,
                'fax_price' => 6,
                'iso_code' => 'YU',
                'continent' => 'Europe',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Zambia',
                'code' => 260,
                'fax_price' => 6,
                'iso_code' => 'ZM',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Zimbabwe',
                'code' => 263,
                'fax_price' => 6,
                'iso_code' => 'ZW',
                'continent' => 'Africa',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Australia',
                'code' => 61,
                'fax_price' => 6,
                'iso_code' => 'AU',
                'continent' => 'Australia and Oceania',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
